### ISSUE TITLE
With mod enabled certain edicts don't work.

### ISSUE THREAD

**Issue by Ebonhawk3829** [altmank/CaptainOfCheats#10]
[COI Saves.zip](https://github.com/altmank/CaptainOfCheats/files/9059441/COI.Saves.zip)

Re; New world.sav
Current consumption at consumer electronics module attached to settlement of 4600 pops is 18.0 / 60s.
Enabling any of the 3 stages of MORE CONSUMER ELECTRONICS edicts, should increase consumption by 25% or more, but there is no change.

Re: Old world.sav
A recyclables collector is attached to settlement and is producing outputs. Expected behavior is altering the recycling efficiency edicts should be reflected in the rate of production of recyclables, however this proves to be untrue in a modded game and the production rate shows negligible difference (attributed to rounding) regardless of which, if any, edicts are enabled.

**Comment by altmank** [comment]
I reviewed New World and the code around Consumer Electronics edict. I did not see any logical way COC code would be interacting with that functionality. Since we can't remove mods, my options are limited here to rule out COC, so was mainly just looking for any logs or signs that there is a logical explanation for an interaction here. None was found. This is the extent of what I can do here, sorry I don't have any additional details here to assist you. I don't have time to debug any deeper than this such as trying other cheat mods or trying to recreate your save in vanilla.

In Old World, you have active use of god mod, and your complaint is about recycling efficiency. God Mode is by dev design (its their cheat internally) not properly setting information about source products when cheating in products. Due to this, I will not be investigating any issues reported about recycling efficiency if God Mod has been used in a save.
