### ISSUE TITLE
Suggestion: Add a button to disable diseases.

### ISSUE THREAD

**Issue by JamieRCHI** [altmank/CaptainOfCheats#23]
**Describe the Suggestion**
I would like to disable the Deadly Diseases in this game.
Is this feasible?

I don't have any issues with illness due to pollution or not enough water in settlements.

**Comment by altmank** [comment]
[CaptainOfCheats_DiseaseCheat.zip](https://github.com/altmank/CaptainOfCheats/files/9622336/CaptainOfCheats_DiseaseCheat.zip)

Want to test it out and let me know how it works for you? Every day change, it checks if the population has a disease, if so, it removes the disease from the population, which mimics what happens when a disease normally expires. It cannot prevent disease, it can only remove it once it happens. This was one of the few implementation options I saw that made sense to implement this in the way COC implements cheats.

**Comment by altmank** [comment]
Note: This will not prevent general population decline due to low health, it will only remove active diseases.

**Comment by altmank** [comment]
I'll probably just push this out and see if anyone complains about it not working right, seems okay from my usual amount of testing I do, which is at least like C+ effort. :)
