### ISSUE TITLE
Source files missing for AssetBundles and a Release file not named correctly.

### ISSUE THREAD

**Issue by JamieRCHI** [altmank/CaptainOfCheats#29]
**Describe the bug**
There is no way to re-create the AssetBundle files without the source code for them. Would be nice to have these source files. 

In the Release files (for the latest version) , the 'bundles.manifest' file should be renamed to 'mafi.bundles.manifest'. This is causing an error in the game log files. (Note that only this file and the 'toolbar_70a1' file are needed in the Assetbundles folder. The rest can be deleted.)

When troubleshooting other mods, it would be very helpful Not to see the log files from this mod. It would be very helpful to add a variable in the code, such as 'LoggingEnabled' that I could set  to 'False' in one of the source files to disable logging. Going through multiple files to comment out the Logging code is very time intensive.

**Comment by altmank** [comment]
Looks like it should actually be mafi_bundles.manifest in the most recent update. Will apply this in the next finished update, thanks!

I don't think I have the unity files anymore so that ship has probably sailed. Not that they were difficult to create, it was just to add in a single icon image into the game.

If you're already at the point of editing this mods code for your own needs, you could just short comment out the logging code in the class (CaptainOfCheats.Logging.Logger), which centralizes all mod specific logging already.
