### ISSUE TITLE
Fehlermeldung Captainofcheats

### ISSUE THREAD

**Issue by razor4495** [altmank/CaptainOfCheats#34]
Hallo 
Ich habe den CaptainofCheats gemäss den Anweisungen Installiert. 
Beim starten eines neuen Spiel mit dem Mod CaptainofCheats kommt folgende Meldung:
![Screenshot 2023-05-31 222931](https://github.com/altmank/CaptainOfCheats/assets/135169113/6280c693-4ffa-417e-9524-11e406f31bce)
![Screenshot 2023-05-31 223825](https://github.com/altmank/CaptainOfCheats/assets/135169113/2389bbfc-4c7b-434a-a626-e2676358440f)

**Comment by MacAttack-UK** [comment]
I can also confirm that since todays (31-05-2023) update v0.5.0A this mod gives this error on launching the game, it worked OK yesterday so I guess we may need an update when your able. Thanks in advance and also for this amazing mod which scratches all of my min/max efficiency iches haha :)
![image](https://github.com/altmank/CaptainOfCheats/assets/13574886/b963f89c-8d4d-4850-af87-b6666e0fa1f8)

**Comment by Elenda86** [comment]
![Unbenannt](https://github.com/altmank/CaptainOfCheats/assets/1834372/a8cb2894-7acc-4eaf-9669-8fb074c0ccb7)

same

**Comment by altmank** [comment]
Fixed in v2.0.1
