### ISSUE TITLE
Terrain Modification - Persist settings & allow explicitly selecting designated areas to mine/dump

### ISSUE THREAD

**Issue by JamieRCHI** [altmank/CaptainOfCheats#6]
Suggestion 1: Would like the 'Disable Terrain Physics' and 'Ignore Tower Designations' settings to default to Off. 
(Possible future enhancement as time permits to add a Settings Tab to let me set the starting defaults?)

Bug?  When 'Ignore Tower Designations' is Off, Tower dump settings still seem to be ignored. 
I have some areas for dumping trash other areas for dirt, and when I select Dirt, and press the Instant Dump,
I get Dirt dumped at all dumping locations, no matter what the towers are set to. 
(This does make sense if the 'Ignore Tower Designations' was set to On.)

Suggestion/Query 2: Would it be feasible to pop up a selection cursor (and hide this dialog) when 'Instant Dump' button is pressed, 
to allow me to select a Mining Tower for the action to be limited to. I just want to focus on one 'Dump Area' at a time.

Edit: Note that when Instant Dump is clicked, the Edge Tiles designating for dumping are not always filled. 
I think this is a bug in the game and not your mod. 
Edit 2: I played around with the Instant Dumping and now I believe I have verified that this is a 'By Design' thing in the Game.
Also I found that it helps in deeper water, to click the Instant Dump button 2 or 3 times to get the desired look, and make the dumping area wider the farther you go from the Island.
[No Pass Here - Sandbox Dump Test.zip](https://github.com/altmank/CaptainOfCheats/files/8985722/No.Pass.Here.-.Sandbox.Dump.Test.zip)

**Comment by altmank** [comment]
@JamieRCHI Hey, thanks for reaching out. 

Suggestion 1:

There was some reasoning behind those defaults. 

Disable terrain physics is the most performant mode as it doesn't require terrain falling calculations. So I chose that as the default as it makes perfect terrain in one click, which is likely what people cheating would expect over the other mode, which requires essentially pressing the button, waiting for the terrain simulation to finish, pressing it again until you get a mound/hole that no longer trigger terrain falling physics, which can be a rather large number of iterations depending how big a terrain change you are making.  I consider the behavior with terrain physics on to be a very poor user experience, so I do not want it as the default. 

Ignore Tower Designations being set to On is meant to protect people from themselves as if you use this mod in a manner like I do, which is mostly playing without cheats, but then occasionally cheating little parts, it is very easy to wipe out your mining pits with this setting set to Off. 

In general I don't plan to change these defaults, but longer term I do plan to persist settings from the cheat menu UI. I think that would solve most of your concern here.

Suggestion 2:
That is likely possible based on what I know of the code. It is also possible to find all designations within a selected area, so another option also could be to allow dragging a box around designations you want to mine/dump.  In general I agree with having a feature that allows the user to be more specific with where the operations happen rather than only with where they don't happen. So I can see this showing up in the future in the mod.

**Comment by altmank** [comment]
Closing as not planned as this mod is mainly in maintenance mode now.
